<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>vsa_w_controller_csharp</RootNamespace>
    <UserSecretsId>11915901-7386-40c5-b165-3548e6ff09f3</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Exception\" />
    <Folder Include="Exception\AuthException\" />
    <Folder Include="Feature\" />
    <Folder Include="Feature\Auth\" />
    <Folder Include="Feature\Auth\Login\" />
    <Folder Include="Feature\Auth\Refresh\" />
    <Folder Include="Feature\Auth\Register\" />
    <Folder Include="Feature\Blog\" />
    <Folder Include="Feature\Blog\CreateBlog\" />
    <Folder Include="Infrastructure\" />
    <Folder Include="Infrastructure\DbConfig\" />
    <Folder Include="Model\" />
  </ItemGroup>

</Project>
