@vsa_w_controller_csharp_HostAddress = http://localhost:5169
@docker_host = http://localhost:8080
@access_token = x-access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiIwMTllYzRiNS1lNzQ4LTc0MDUtOWQxYy0xZjllNDU4NWRlOTQiLCJ1c2VybmFtZSI6ImV4YW1wbGUxMjMiLCJleHAiOjE3ODE4MTY1Mjd9.vp_i_yUYkp7ykdmEMTC4QN99K7vv86t-TI1tKgSjkQo
@refresh_token = x-refresh-token=rqcuODdxIqS%2BQ264AZHW%2Fx3mCAF5aI50qdHM14S6ZbfQvR5e1hIoQwrhh6KAhsF8FeQnzVAygLE%2F12IuBkfbGg%3D%3D

GET {{vsa_w_controller_csharp_HostAddress}}/weatherforecast/
Accept: application/json


### User Register

POST {{docker_host}}/api/v1/vsac/auth/register
Content-Type: application/json
Accept: application/json

{
    "username": "example123",
    "password": "example123"
}

### User Login
POST {{vsa_w_controller_csharp_HostAddress}}/api/v1/vsac/auth/login
Content-Type: application/json

{
    "username": "example123",
    "password": "example123"
}

### User Refresh Token
POST {{vsa_w_controller_csharp_HostAddress}}/api/v1/vsac/auth/refresh
Content-Type: application/json
Cookie: {{refresh_token}}


### User create blog

POST {{vsa_w_controller_csharp_HostAddress}}/api/v1/vsac/blog/new-blog
Content-Type: application/json
Cookie: {{access_token}}
Accept: application/json

{
    "Title": "Example1",
    "Description": "Testing",
    "Content": "Testing"
}


### Get all blog from current user
GET {{vsa_w_controller_csharp_HostAddress}}/api/v1/vsac/blog/all-blog?PageSize=1000&PageIndex=1
Accept: application/json
Cookie: {{access_token}}


### Get single blog from user/or current user

GET {{vsa_w_controller_csharp_HostAddress}}/api/v1/vsac/blog/read/019edc1e-ae60-700a-918e-c72e9ff189e0
Accept: application/json
Cookie: {{access_token}}


### Update a blog
PATCH {{vsa_w_controller_csharp_HostAddress}}/api/v1/vsac/blog/edit/019ecc2d-9963-741c-a6c7-410e1151479f
Accept: application/json
Cookie: {{access_token}}
Content-Type: application/json

{
    "title":"tt3",
    "description":"tt3",
    "content":"tt3"
}


### Delete A Blog
DELETE {{vsa_w_controller_csharp_HostAddress}}/api/v1/vsac/blog/deactive-blog?BlogId=019edc1e-ae60-700a-918e-c72e9ff189e0
Accept: application/json
Cookie: {{access_token}}