@vsa_w_controller_csharp_HostAddress = http://localhost:5169
@docker_host = http://localhost:8080
@access_token = x-access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiIwMTllYzRiNS1lNzQ4LTc0MDUtOWQxYy0xZjllNDU4NWRlOTQiLCJ1c2VybmFtZSI6ImV4YW1wbGUxMjMiLCJleHAiOjE3ODI1OTc2OTV9.vkJQdZB1p3KkFDI-6w8uRFnQ5bhCoOcxwr5P_9k12oQ
@refresh_token = x-refresh-token=rqcuODdxIqS%2BQ264AZHW%2Fx3mCAF5aI50qdHM14S6ZbfQvR5e1hIoQwrhh6KAhsF8FeQnzVAygLE%2F12IuBkfbGg%3D%3D
@presigned_url = https://amcyjsdejcdianlhhwkt.storage.supabase.co/storage/v1/s3/products/path/2026/06/996a711d-b24e-44e7-b4f1-95dba90bb255.png?X-Amz-Expires=300&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=dfb7ccf08a59fe4135f9ada22023ebac%2F20260627%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260627T202511Z&X-Amz-SignedHeaders=host&X-Amz-Signature=ed5a0d35877e4a1c7af0ac4bb75244966c92168468cc6dab5db5ae67fdde66c3

GET {{vsa_w_controller_csharp_HostAddress}}/weatherforecast/
Accept: application/json


### User Register

POST {{docker_host}}/api/v1/vsac/auth/register
Content-Type: application/json
Accept: application/json

{
    "username": "example123",
    "password": "example123"
}

### User Login
POST {{vsa_w_controller_csharp_HostAddress}}/api/v1/vsac/auth/login
Content-Type: application/json

{
    "username": "example123",
    "password": "example123"
}

### User Refresh Token
POST {{vsa_w_controller_csharp_HostAddress}}/api/v1/vsac/auth/refresh
Content-Type: application/json
Cookie: {{refresh_token}}


### Create a blog

POST {{vsa_w_controller_csharp_HostAddress}}/api/v1/vsac/blog/new-blog
Content-Type: application/json
Cookie: {{access_token}}
Accept: application/json

{
    "Title": "Example5",
    "Description": "Testing5",
    "Content": "Testing5",
    "StorageKey": [
        "path/2026/06/996a711d-b24e-44e7-b4f1-95dba90bb255.png"
    ]
}


### Upload image through presigned url
PUT {{presigned_url}}
Content-Type: image/png

< C:\Users\admin\Pictures\saber.png


### Get all blog from current user
GET {{vsa_w_controller_csharp_HostAddress}}/api/v1/vsac/blog/all-blog?PageSize=1000&PageIndex=1
Accept: application/json
Cookie: {{access_token}}


### Get single blog from user/or current user

GET {{vsa_w_controller_csharp_HostAddress}}/api/v1/vsac/blog/read/019f0ac2-832c-7c88-b5a1-a8e05a38a745
Accept: application/json
Cookie: {{access_token}}


### Get newest blog for new feed
GET {{vsa_w_controller_csharp_HostAddress}}/api/v1/vsac/blog/feed?PageIndex=1&PageSize=1000&FromDate=01/01/2025&ToDate=07/30/2026
Accept: application/json
Cookie: {{access_token}}


### Update a blog
PATCH {{vsa_w_controller_csharp_HostAddress}}/api/v1/vsac/blog/edit/019ecc2d-9963-741c-a6c7-410e1151479f
Accept: application/json
Cookie: {{access_token}}
Content-Type: application/json

{
    "title":"tt3",
    "description":"tt3",
    "content":"tt3"
}


### Delete A Blog
DELETE {{vsa_w_controller_csharp_HostAddress}}/api/v1/vsac/blog/deactive-blog?BlogId=019edc1e-ae60-700a-918e-c72e9ff189e0
Accept: application/json
Cookie: {{access_token}}



### Upload image
POST {{vsa_w_controller_csharp_HostAddress}}/api/v1/vsac/image/upload
Cookie: {{access_token}}
Content-Type: application/json

{
    "FileFormat": [
        "png"
    ]
}